# Site settings
title: Angelo Passaro
description: 'Business Card Page'
url: '127.0.0.1'
baseurl: ''
profilepic: '/images/profile.png'
bkimage: '/images/bk2.jpg'
#google_analytics: UA-XXXXXX-X
#font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Angelo Passaro'
#  email: 
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  angelopassaro
  working: Student
  linkedin_username: angpas
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
kramdown:
  syntax_highlighter: rouge
  input: GFM


collections:
  writeup:
    output: true

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
